---

- hosts: all
  become: true
  tasks: 

  - name: Manually download packages for Fedora
    get_url:
      name:
        - git
        - 
      state: latest
    when: ansible-distribution == "Fedora" 
