---

- hosts: remote01:zserv
  become: true
  pre_tasks:
  - name: Updating package repo
    ansible.builtin.apt:
      name: "*"
      update_cache: yes
      state: latest
      autoremove: yes
      autoclean: yes

  - name: Download GPG Key
    ansible.builtin.get_url: 
      url: https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg
      dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
  
  - name: Download GPG Key
    ansible.builtin.get_url:
      url: https://pkgs.tailscale.com/stable/ubuntu/focal.tailscale-keyring.list
      dest: /etc/apt/sources.list.d/tailscale.list
  
  - name: Install Tailscale
    ansible.builtin.apt:
      name: tailscale
  
  - name: Start Tailscale
    ansible.builtin.service:
      name: tailscaled
      enabled: yes
      state: started

