---

- hosts: all
  become: true
  tasks:

  - name: install docker plugins
    dnf:
      name:
        - dnf-plugins-core
      state: latest

  - name: install docker repo
    enablerepo: https://download.docker.com/linux/fedora/docker-ce.repo  
      
      line: 
  - name: install docker files and docker-compose
    dnf:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose
      state: latest        