---

- hosts: all
  become: true
  tasks:

  - name: install docker plugins
    dnf:
      name:
        - dnf-plugins-core
      state: latest

  - name: add docker repository
    lineinfile:
      state: present
      insertafter: EOF
      path: /etc/dnf/dnf.conf
      marker: "<! -- Ansible Managed Block -- >"
      content: |
        https://download.docker.com/linux/fedora/docker-ce.repo        