---

- hosts: all
  become: true
  tasks:

  - name: install docker plugins
    dnf:
      name:
        - dnf-plugins-core
      state: latest

  - name: add docker repository
    lineinfile:
      state: present
      path: /etc/dnf/dnf.conf
      insertafter: EOF
      line: https://download.docker.com/linux/fedora/docker-ce.repo  
      
  - name: install docker files and docker-compose
    dnf:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose
      state: latest        