---

- hosts: all
  become: true
  tasks:

  - name: Download rclone rpm
    get_url:
      url: https://downloads.rclone.org/rclone-current-linux-amd64.rpm
      dest: /home/zantop/files
  
  - name: Install downloaded Rclone rpm
    dnf:
      name: /home/zantop/files/rclone-current-linux-amd64.rpm
      state: present
      disable_gpg_check: true
      

