---

#Used for testing new code quickly
- hosts: remote01:zserv
  become: true
  tasks:
    - name: update_cache
      ansible.builtin.apt:
        name: "*"
        update_cache: yes
        state: latest

    - name: Install Plex
      ansible.builtin.apt:
        deb: https://downloads.plex.tv/plex-media-server-new/1.40.1.8227-c0dd5a73e/debian/plexmediaserver_1.40.1.8227-c0dd5a73e_amd64.deb


    

