---

#Used for testing new code quickly
- hosts: remote01:zserv
  become: true
  tasks:
    - name: update_cache
      ansible.builtin.apt:
        name: "*"
        update_cache: yes
        state: latest

    - name: Install Plex
      ansible.builtin.apt:
        deb: https://downloads.plex.tv/plex-media-server-new/1.40.1.8227-c0dd5a73e/debian/plexmediaserver_1.40.1.8227-c0dd5a73e_amd64.deb


    - name: Install Jellyfin
      ansible.builtin.apt:
        deb: https://repo.jellyfin.org/files/server/debian/latest-stable/amd64/jellyfin-server_10.8.13-1_amd64.deb
    
    - name: Enable Jellyfin Service
      ansible.builtin.service:
        name: jellyfin
        state: started
        enabled: yes
