---

#Used for testing new code quickly
- hosts: remote01:zserv
  become: true
  tasks:
    - name: update_cache
      ansible.builtin.apt:
        name: "*"
        update_cache: yes
        state: latest